titre: "Tarn.Comobi"
mail: "tarn.comobi@otema-tsa.fr"
tel: "07 81 46 16 28 - 06 33 77 62 40"
nom: "Tarn.Comobi"
formulaire: "https://docs.google.com/forms/d/1JMiPKb69tEFLCoPCuyEmCShHIRs9raC8XLileZTRTVE/viewform?usp=sf_link"
formulaire_passager: "https://docs.google.com/forms/d/e/1FAIpQLScfZKk6qeVPw3zDVHnYl2Hzw6urgAXRYBXftW1WNb7CA325mA/viewform?usp=sf_link"
lien_cgu: "/cgu"

couleurs: 
  bouton_rechercher: "#199bb0"
  bouton_proposer: "#22aa75"
  odd_section_color: "#ecf0f1"
  header_btn_section: "white"

bandeau:
  image: "/images/bannierecomobi1.png"
  texte: "Bandeau Comobi Tarn"

## Les sections suivantes ne sont pas à modifier
sass:
  sass_dir: _sass
  style: compressed

exclude:
  - direct/
  - outil-metier/

include:
  - _config.yml 

keep_files:
  - _config.yml 

code_source:
  instance: "https://github.com/betagouv/tarn.comobi.fr"
  comobi: "https://github.com/betagouv/comobi"

defaults:
- scope:
    path: "assets/img"
  values:
    image: true
